### ISSUE TITLE
Update for Quic-Go v0.13.1

### ISSUE THREAD

**Issue by Flameborn** [techknowlogick/caddy-s3browser#39]
Currently, there is no _go.mod_ file specified in the project. As a result, Go pulls in the latest Quic-Go (v0.13.1)

This release has a folder rename, from _github.com/lucas-clemente/quic-go/h2quic_ to _github.com/lucas-clemente/quic-go/http3_.

Currently, Caddy v1.0.4 is not able to build with this plugin added.

**Comment by techknowlogick** [comment]
There is a go.mod file here: https://github.com/techknowlogick/caddy-s3browser/blob/master/go.mod, I've tried to do a `go get -u` however it's failing due to an upstream dependancy:
```
# github.com/caddyserver/caddy/caddyhttp/httpserver
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:281:14: undefined: blackfriday.HtmlRenderer
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:283:11: undefined: blackfriday.EXTENSION_TABLES
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:284:11: undefined: blackfriday.EXTENSION_FENCED_CODE
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:285:11: undefined: blackfriday.EXTENSION_STRIKETHROUGH
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:286:11: undefined: blackfriday.EXTENSION_DEFINITION_LISTS
../../../../pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/tplcontext.go:287:34: too many arguments to conversion to blackfriday.Markdown: blackfriday.Markdown([]byte(body), renderer, extns)
```

**Comment by Flameborn** [comment]
I'm sorry, it seems like I missed this for some reason. Either that, or Github's search had a bad day.

I am not getting the Blackfriday  error via Go 1.13.4. This might be a dependency clash, though interestingly, _go mod why h2quic_ is the import root, via _caddy-s3browser_.

**Comment by techknowlogick** [comment]
I've since upgraded the dependencies, and have tested that caddy's build server can compile with this plugin and so I will close this. If you are still experiencing this please re-open :)
