### ISSUE TITLE
Customize timeframe for re-fetching of file listing

### ISSUE THREAD

**Issue by mcrosson** [techknowlogick/caddy-s3browser#4]
Does the plugin require caddy to be restarted if the files shown from a minio bucket are changed?

I've got an azure gateway setup with minio + s3browser and it seems like I need to restart caddy to pickup folder changes at a minimum.

**Comment by techknowlogick** [comment]
It should trigger every 5 minutes a regen of the file listing per https://github.com/techknowlogick/caddy-s3browser/blob/master/setup.go#L43

This is for caching purposes, as the bucket I'm personally using it has thousands of files.

Would having the timeout be an option that you'd like?

**Comment by mcrosson** [comment]
@techknowlogick I was just poking at the listings as part of some rclone work I was doing and realized that it wasn't refreshing like I anticipated.

If you added a note to the readme/docs that'd be more than sufficient IMHO. Now that I know it's a 5 minute cache I'm good to go.

I don't need any special time out flag at this time and 5 minutes is a good time frame for caches. If I did anything I'd probably increase it to an hour or more for my needs.

**Comment by mcrosson** [comment]
Actually... now that I think on it I may actually be OK with disabling any regeneration of the cache and just restarting caddy whenever new files come online...

I'm using the plugin for a downloads site and they don't change often, only adds once a week or so.

**Comment by techknowlogick** [comment]
Added note about the timeframe to README, but I'm going to keep this ticket open so I can eventually add a flag to allow customization.

**Comment by techknowlogick** [comment]
Closing as I've added refresh to be configurable.
