### ISSUE TITLE
Not showing full bucket contents

### ISSUE THREAD

**Issue by mcrosson** [techknowlogick/caddy-s3browser#5]
On https://dl.lollipopcloud.solutions/armbian/hdmi/ there should be an "attic" folder as well.

I'm using s3browser in front of minio in setup as an azure blob storage gateway.

I've checked minio with the mc tool as well as the azure blob storage and they both show the "attic" folder. I've also restarted caddy with no effect.

Is there a limit to how many files/folders/etc that are enumerated by s3browser?

**Comment by techknowlogick** [comment]
It fetches all of them, however it seems that it isn't listing the folders in that directory. If you go to https://dl.lollipopcloud.solutions/armbian/hdmi/attic/ directly you can see the files in that directory, as well as even download them.

**Comment by techknowlogick** [comment]
Hey @mcrosson I've just pushed a fix that 1. cleans up some pretty messy code, and 2. properly generates folder tree, which means that it should fix the issue you have been seeing.
