### ISSUE TITLE
Error during parsing: unrecognized directive: s3browser

### ISSUE THREAD

**Issue by jonbloom** [techknowlogick/caddy-s3browser#83]
Hi,

I've built caddy 2 from source via xcaddy with the following command: 
`./go/bin/xcaddy build --output ./caddy --with github.com/techknowlogick/caddy-s3browser --with github.com/caddy-dns/cloudflare`

Here's the redacted Caddyfile I've been testing with:
```
example-domain.com {
                s3browser {
                        endpoint nyc3.digitaloceanspaces.com
                        region nyc3
                        key <key>
                        secret <secret>
                        bucket <bucket>
                        debug true
                }
}
```

When I try to validate the file to ensure it will work, I get the following error: 

> Error during parsing: unrecognized directive: s3browser

Any ideas? What may I be missing to get this going?

**Comment by rossmeier** [comment]
I got the same problem, the module isn't even listed in `caddy list-modules`. Also on the caddy download page, the module info is missing.

**Comment by rossmeier** [comment]
Updating all dependencies with go get -u fixes the problem for me.

**Comment by techknowlogick** [comment]
@veecue would you be willing to submit a PR with those changes?

**Comment by rossmeier** [comment]
@techknowlogick I think that I fixed the go.mod and dockerfiles so far. CI is still missing (I tried adapting most of the stuff to use xcaddy)

**Comment by techknowlogick** [comment]
Very awesome!! Thanks so much :) If I can provide any guidance please let me know.

**Comment by rossmeier** [comment]
FYI: You might need to specify the version of caddy-s3browser to use like this: `./go/bin/xcaddy build --output ./caddy --with github.com/techknowlogick/caddy-s3browser@master --with github.com/caddy-dns/cloudflare`
