### ISSUE TITLE
Listing sort

### ISSUE THREAD

**Issue by ThinkChaos** [techknowlogick/caddy-s3browser#87]
I think some built-in sorting mechanism would benefit everyone, as right now we just reuse S3's order which AFAICT isn't specified.

I have a (currently private) patch to sort dirs/files case-insensitively and also noticed that on https://dl.gitea.io/gitea there seems to be some sorting done.

Is the code for dl.gitea.io public? I couldn't find it. I'd like to see if I can merge that and my version and submit a PR here.

**Comment by techknowlogick** [comment]
dl.gitea.io uses the `caddy-v1` branch with includes customization for sorting via semver. I'd be open to accepting a PR for sorting to `master` branch be it the semver from the other branch, or the sorting that you have a patch for (or both).

**Comment by ThinkChaos** [comment]
Oh thanks, I hadn't looked at that branch since I ported the code to Caddy 2.
I cherry-picked the commit for semsort (6d590fefb21c4cf39902e6e865f961e151837eb7) on top of master, and with minor changes it's working.

What I'm thinking of doing is changing the `semantic_sort` option to `sort_algorithm $algorithm [reverse]`. Where `$algorithm` could be `alphabetical` (default), `case-insensitive`, `semver`. And if the `reverse` modifier is present, reverse the sort's result.  
Maybe supporting `$algorithm == none` would be useful but I doubt it.

My use case doesn't require different sorting for dirs/files (still keeping them separate of course), and I don't think dl.gitea.io needs it either, so I haven't put any thought into that.

How does that plan sound?

**Comment by techknowlogick** [comment]
That sounds like a great plan, thank you again for your contributions to this project :)
