### ISSUE TITLE
Building with xcaddy requires @master

### ISSUE THREAD

**Issue by redturtlepower** [techknowlogick/caddy-s3browser#90]
Building a custom `caddy` the standard way (read "I think this is the standard") does not succeed:
```
FROM caddy:2.3.0-builder AS builder
RUN xcaddy build v2.3.0 \
  --with github.com/techknowlogick/caddy-s3browser
```
`caddy list-modules | grep s3browser` does return 1, aka the module is not included. 

This solved the problem for me: 
```
  --with github.com/techknowlogick/caddy-s3browser@master
```
This might be obvious to golang experts? I don't know yet how go/xcaddy "finds" the correct commits or modules to build from, so I can't propose a code change. In case my issue is valid, can you document this requirement somewhere?

**Comment by techknowlogick** [comment]
Thanks for raising this issue, I've just renamed the `master` branch to `main` due to prompting from github, but I'll document this in the README using the new branch name.
