### ISSUE TITLE
Still maintained? 

### ISSUE THREAD

**Issue by hevisko** [techknowlogick/caddy-s3browser#94]

**Comment by hevisko** [comment]
pressed enter too quick and then I can't delete it ;(

**Comment by techknowlogick** [comment]
Hi, that's ok. Yes, it is being maintained :) It's in a fairly stable place, and for my purposes all the features I need have been added, so I just make sure that dependencies are kept up to date and keeps on being able to be built with the latest version of caddy.

**Comment by hevisko** [comment]
what bite my last night: not having the `@main` at the end, which 'causes this error:

```
/root/go/pkg/mod/github.com/caddyserver/caddy@v1.0.4/caddyhttp/httpserver/server.go:107:33: unknown field 'Server' in struct literal of type http3.Server
```

appending `@main` to s3-browser makes it work - strange...
